### ISSUE TITLE
Hjelp! 

### ISSUE THREAD

**Issue by kejnim** [NimaAB/Oblig1-DATA1600#2]
Trenger en bedre regex.pattern for nummer telefon.  Du kan legge ekspresjonen i Valinderinger.java tlfnrValidate metode.

**Comment by glaysa** [comment]
Skal vi ikke ta hensyn på landskoder til tlf nummeret? Jeg har sjekket din kode og den tar ikke inn landskoder.

**Comment by kejnim** [comment]
Den tar inn landkode og vanlig nummer, men landkode må alltid begynne med 00 for at koden min skal godkjenne. Jeg tenkte om å finne et bedre regex pattern for å ta i mot + isteden for 00 også.

**Comment by glaysa** [comment]
jeg har en kode for det. Jeg har lagret landskoder som er gyldige i et array og setter den sammen med regexen. Jeg kan sende deg en txt fil på metoden jeg har laget. Min kode har litt annerledes oppsett men bare se om det hjelper. 

[tlfvalidering.txt](https://github.com/NimaAB/Oblig1-DATA1600/files/4141480/tlfvalidering.txt)

**Comment by kejnim** [comment]
Ser veldig bra ut. jeg skal nærmere på den imorgen.

**Comment by glaysa** [comment]
[tlfvalidering2.txt](https://github.com/NimaAB/Oblig1-DATA1600/files/4142929/tlfvalidering2.txt)
[readFile.txt](https://github.com/NimaAB/Oblig1-DATA1600/files/4142931/readFile.txt)
[parseCountryCodes.txt](https://github.com/NimaAB/Oblig1-DATA1600/files/4142934/parseCountryCodes.txt)
[landskoder.txt](https://github.com/NimaAB/Oblig1-DATA1600/files/4142947/landskoder.txt)
